plugin:
  debug: false 
  # some plugins, like AuthMe protects the NPC
  # if your NPC take no damage set these value to true
  # WARNING: everybody can kill the NPC if these value is true
  overwriteAllNpcDamageListener: false
  printMessages: true
  # options: automaticDownload, onlyNotify or off
  autoupdate: notify 
npc:
  # valid colors: http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes
  nameTagColor: 'f'
  # options: vanilla or none
  expdrop: vanilla
  spawn:
    onlyIfPlayerNearby: true
    distance: 8
    time: 10
    additionalTimeIfUnderAttack: 15
    broadcastMessageRadius: 32
language:
  npcSpawned: NPC spawned
  npcKilled: <Player>s NPC has been killed while combat logged
  yourNPCKilled: Your NPC has been killed while combat logged
metrics:
  # activate/deactivate metrics graphs opt-out
  listenerMode: true
  worldGuardUsage: true
  factionsUsage: true