plugin:
  debug: false 
  # some plugins, like AuthMe protects the NPC
  # if your NPC take no damage set these value to true
  # WARNING: everybody can kill the NPC if these value is true
  overwriteAllNpcDamageListener: false
npc:
  spawn:
    onlyIfPlayerNearby: true
    distance: 8
    time: 10
    additionalTimeIfUnderAttack: 15
    broadcastMessageRadius: 32
language:
  npcSpawned: NPC spawned
  npcKilled: <Player>s NPC has been killed while combat logged
  yourNPCKilled: Your NPC has been killed while combat logged
        