name: DragonAntiPvPLeaver
author: IDragonfire, DylanHolmes
version: 2.0
main: com.github.idragonfire.DragonAntiPvPLeaver.DAntiPvPLeaverPlugin
depend: [RemoteEntities]
soft-depend: [WorldGuard, Factions]
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features