name: DragonAntiPvPLeaver
author: DylanHolmes, IDragonfire
version: 1.5
main: com.github.idragonfire.DragonAntiPvPLeaver.DAntiPvPLeaverPlugin
soft-depend: [WorldGuard, Factions]
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features