name: DragonAntiPvPLeaver
author: IDragonfire, DylanHolmes
version: 1.6
main: com.github.idragonfire.DragonAntiPvPLeaver.DAntiPvPLeaverPlugin
soft-depend: [WorldGuard, Factions]
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features