name: DragonAntiPvPLeaver
author: DylanHolmes, IDragonfire
version: 1.2
main: com.github.idragonfire.DragonAntiPvPLeaver
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features