name: DragonAntiPvPLeaver
author: IDragonfire
version: 2.0
main: com.github.idragonfire.DragonAntiPvPLeaver.Plugin
depend: [RemoteEntities]
soft-depend: [WorldGuard, Factions]
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features