name: DragonAntiPvPLeaver
author: DylanHolmes, IDragonfire
version: 1.2
main: com.github.idragonfire.DragonAntiPvPLeaver.DragonAntiPvPLeaverPlugin
soft-depend: [WorldGuard]
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features