name: DragonAntiPvPLeaver
author: DylanHolmes, IDragonfire
version: 1.3
main: com.github.idragonfire.DragonAntiPvPLeaver.DAntiPvPLeaverPlugin
soft-depend: [WorldGuard]
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features